export type Event = {
    id: number;
    title: string;
    date: string;
    time: string;
    venue: string;
    price: string;
    image: string;
    organizer: string;
};

export type CategorizedEvent = {
    category: string;
    events: Event[];
};

export const categorizedEvents: CategorizedEvent[] = [
    {
        category: "Music Concerts",
        events: [
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },
            {
                id: 1,
                title: "Wonder Girls 2010 Wonder",
                date: "1 June 2025",
                time: "05:00 PM",
                venue: "Rupas Mall, Eldoret",
                price: "Kshs 3000",
                image: "https://i.imgur.com/6Iej2c3.jpg",
                organizer: "EMB Events",
            },

        ],
    },
    {
        category: "Tech Conferences",
        events: [
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },
            {
                id: 2,
                title: "Tech Africa Summit 2025",
                date: "15 Aug 2025",
                time: "10:00 AM",
                venue: "Safari Park, Nairobi",
                price: "Kshs 5000",
                image: "https://i.imgur.com/fHyEMsl.jpg",
                organizer: "DevConnect",
            },

        ],
    },
];
